use_frameworks!

platform :ios, '14.3'

target 'AnimalAnalyzer_Example' do
  pod 'AnimalAnalyzer', :path => '../'

  target 'AnimalAnalyzer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
